dist: trusty
sudo: required

language: node_js
node_js:
  - "10"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e --protractor-config=projects/admin/e2e/protractor-ci.conf.js

before_deploy:
  - ng build --prod

deploy:
  provider: firebase
  project: "ibuteco-ce9c3"
  token:
    secure: "$FIREBASE_TOKEN"
  on:
    branch: master
